[Platforms]
WindowsArguments = fontengine=freetype

[QPA]
platformName = windows

[Qt]
HighDpiScaling = true
UseHighDpiPixmaps = true
HighDpiScaleFactorRoundingPolicy = PassThrough
AutoScreenScaleFactor = true

[WebEngine]
DisableSandbox = false
ChromiumFlags = --use-angle=d3d11 --enable-features=UseSkiaRenderer,CanvasOopRasterization,ZeroCopy --disable-background-timer-throttling
