"""协议化上传引擎基础模块。"""

from .engine import ProtocolPublishEngine, ProtocolRunContext
from .models import (
    ProtocolCaptureArtifact,
    ProtocolCaptureEntry,
    ProtocolExecutionPlan,
    ProtocolStageDefinition,
)
from .dry_run import ProtocolDryRunError, build_protocol_dry_run, merge_freight_probe_summary, normalize_record_snapshot
from .stages import (
    BasicPublishStageDependencies,
    CategoryAttributesStageExecutor,
    CategorySelectionStageExecutor,
    MediaStageDependencies,
    MediaStageExecutor,
    MainImagesStageExecutor,
    OpenPublishPageStageDependencies,
    OpenPublishPageStageExecutor,
    PriceStockStageDependencies,
    PriceStockStageExecutor,
    PublishSessionStageDependencies,
    PublishSessionStageExecutor,
    SkuEntriesStageExecutor,
    SkuStageDependencies,
    SkuStructureStageExecutor,
    SubmitPublishStageDependencies,
    SubmitPublishStageExecutor,
    TitleStageExecutor,
)

__all__ = [
    "ProtocolPublishEngine",
    "ProtocolRunContext",
    "ProtocolCaptureArtifact",
    "ProtocolCaptureEntry",
    "ProtocolExecutionPlan",
    "ProtocolStageDefinition",
    "ProtocolDryRunError",
    "build_protocol_dry_run",
    "merge_freight_probe_summary",
    "normalize_record_snapshot",
    "BasicPublishStageDependencies",
    "CategoryAttributesStageExecutor",
    "CategorySelectionStageExecutor",
    "OpenPublishPageStageDependencies",
    "OpenPublishPageStageExecutor",
    "MediaStageDependencies",
    "MediaStageExecutor",
    "MainImagesStageExecutor",
    "PriceStockStageDependencies",
    "PriceStockStageExecutor",
    "PublishSessionStageDependencies",
    "PublishSessionStageExecutor",
    "SkuEntriesStageExecutor",
    "SkuStageDependencies",
    "SkuStructureStageExecutor",
    "SubmitPublishStageDependencies",
    "SubmitPublishStageExecutor",
    "TitleStageExecutor",
]
